### ISSUE TITLE
小米14澎湃os,安卓14内核不可用

### ISSUE THREAD

**Issue by lijingyang275** [670848654/MoviesBox#1]
点开动漫会是黑屏
![Screenshot_2024-04-24-21-11-31-710_my project moviesbox](https://github.com/670848654/MoviesBox/assets/46836377/ca34d5e8-6d8c-4b00-ba3d-23f75940011c)

**Comment by lijingyang275** [comment]
怎么查具体错误信息啊，我可以进入主页，但是点开任何一个动漫就是这样
![Screenshot_2024-04-25-00-05-29-730_my project moviesbox](https://github.com/670848654/MoviesBox/assets/46836377/145ef366-dd0c-4480-859f-994bbb453d86)
![Screenshot_2024-04-25-00-05-35-475_my project moviesbox](https://github.com/670848654/MoviesBox/assets/46836377/46fcf086-53fe-4e23-8b20-5f6e61fabdd4)

**Comment by 670848654** [comment]
是否root安装了相关存储模块/插件？看着应该为权限问题

lijingyang275 ***@***.***> 于 2024年4月25日周四 上午12:06写道：

**Comment by lijingyang275** [comment]
没有root,那我给一下权限看看

**Comment by lijingyang275** [comment]
还是不行，能给的权限都给了

**Comment by 670848654** [comment]
> 还是不行，能给的权限都给了

尝试新版本

**Comment by lijingyang275** [comment]
已可正常观看，感谢大佬
![Uploading Screenshot_2024-04-25-22-52-11-292_my.project.moviesbox.jpg…]()
