### ISSUE TITLE
是否考虑添加站点？

### ISSUE THREAD

**Issue by mavnp** [670848654/MoviesBox#2]
请问有添加站点的打算吗？
譬如：
厂长影视：https://www.cz01.vip/
低端：https://ddys.info
缘觉影视：https://www.bdys.me
两个bt：https://bttwo.vip
素白白影视：https://subaibai.vip

**Comment by 670848654** [comment]
暂时没有，首先没有什么时间来搞事情，其次站点太多难以维护，以后可能有规划

mavnp ***@***.***> 于 2024年6月2日周日 下午4:56写道：
