### ISSUE TITLE
libvio线路缺少

### ISSUE THREAD

**Issue by mavnp** [670848654/MoviesBox#3]
《金田一少年事件簿》在原网站有HD播放和HD2播放两条线路，而在MoviesBox应用内只有一条线路

![Screenshot_20240602_170635_my.project.moviesbox.jpg](https://github.com/670848654/MoviesBox/assets/92003405/892b0214-89a5-4ec9-8f5b-eb7983702976)

![Screenshot_20240602_170642_mark.via.jpg](https://github.com/670848654/MoviesBox/assets/92003405/f3c97f58-d74e-423c-8018-f377494a1655)

**Comment by 670848654** [comment]
看了下，这是个bug，下个版本修复

mavnp ***@***.***> 于 2024年6月2日周日 下午5:10写道：
